### ISSUE TITLE
After updating baseline image, change is not reflected in 'suite' view

### ISSUE THREAD

**Issue by tk8817** [wearefriday/spectre#15]
Can provide screenshots if required

**Comment by nickdunn** [comment]
I think I've spotted this too but unsuccessfully diagnosed. A screenshot would be useful, yes please.

**Comment by nickdunn** [comment]
@tk8817 do you happen to have a screenshot to show this behaviour please?

**Comment by nickdunn** [comment]
Solved in #19.
