### ISSUE TITLE
Test name should anchor to scroll like "Set as baseline" button

### ISSUE THREAD

**Issue by nickdunn** [wearefriday/spectre#23]
When scrolling through tall screenshots it's really useful that the "Set as baseline" button anchors to the top of the screen, but it's annoying that the test name on the left doesn't do the same. I forget what test I'm looking at.

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
