### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bjankord** [wearefriday/spectre#24]
Hey wearefriday, thanks for this project. Our team is exploring using spectre for visual regression testing paired with screenshots from https://saucelabs.com/. One of the things we were curious about is if you are planning to add a license (MIT, Apache-2.0, ISC, etc)?

**Comment by windse7en** [comment]
From the [blog](https://medium.com/friday-people/how-we-do-visual-regression-testing-af63fa8b8eb1#.46xsglwre), it mentioned spectre will be open source. Do you mind to upload the LICENSE?
![bitmoji](https://render.bitstrips.com/v2/cpanel/10212045-181571342_2-s4-v1.png?transparent=1&width=246)

**Comment by nickdunn** [comment]
@bjankord great! I'd love to know how you get on. Let me know if you'd like any assistance getting set up. We have a couple of (fairly messy) Ruby scripts we currently use to pump screenshots into Spectre that I could share.

Licence is on its way — MIT.

**Comment by nickdunn** [comment]
Added in #25.
