### ISSUE TITLE
Needs docs for from-scratch setup

### ISSUE THREAD

**Issue by nickdunn** [wearefriday/spectre#27]
As per @klamping's woes in https://www.youtube.com/watch?v=PRRdGR0VfqI, the readme probably needs walk-through for both a from-scratch setup and using Docker.

From scratch setup along the lines of:
1. Installing rvm to get the required ruby version
2. Installing bundler and running bundle install
3. Installing postgres (either homebrew or http://postgresapp.com/) and connecting to it
4. Installing imagemagick

**Comment by YmerejRedienhcs** [comment]
@nickdunn Any chance of movement on this?  We'd really like to get this up and running, and could use some details on deploying both locally and with Docker.  Thanks!

**Comment by YmerejRedienhcs** [comment]
Thanks so much!  I was able to follow the instructions and see spectre in action using Docker.

**Comment by nickdunn** [comment]
Great! Thanks for confirming.

**Comment by mansn** [comment]
It seems that installing rmagick on Windows is a bit tricky to get done, and Spectre depends on rmagick. I got it installed by following this article:
https://medium.com/ruby-on-rails-web-application-development/install-rmagick-gem-on-windows-7-8-10-imagemagick-6-9-4-q16-hdri-5492c3fef202

Also, unicorn (HTTP Server) doesn't support Windows. Maybe it would be nice to include suggested alternatives for Windows users? I'm currently trying with [Thin](http://code.macournoyer.com/thin/).

Thanks for a really neat UI!
