### ISSUE TITLE
Has the "width" parameter been replaced/renamed to "size"? (POST /tests)

### ISSUE THREAD

**Issue by mansn** [wearefriday/spectre#28]
Hi,

The README.md says that you should include a "width" parameter (among other parameters) when making a POST request to /tests (to submit a screenshot). However, I'm getting a validation error that "Size can't be blank" when following those instructions. When I look into tests_controller.rb, then I don't see any "width" parameter being required, but I see a "size" parameter which is required. So I renamed my "width" parameter to "size" and my POST request was successful. Should the readme be updated?

**From the README.md:**
Then you can submit a screenshot!

```
POST /tests
      test:
        run_id: {run_id from above},
        name: Homepage,
        platform: OSX,
        browser: PhantomJS,
        width: 1024,
        screenshot: <File>
```

**Comment by nickdunn** [comment]
Hey @mansn thanks for the bug report. Yes indeed, the readme is wrong and should say `screen`. It used to be `width` but we renamed it to be more generic so it could support any sort of form factor (e.g. `desktop`, `mobile`, `tablet` or `full template` and `partial component` or whatever naming convention makes sense for you).

**Comment by nickdunn** [comment]
Fixed in https://github.com/wearefriday/spectre/commit/7522a22287a31e38de7343442c10df5c3a5676c0.

**Comment by mansn** [comment]
That was fast! Highly appreciated!
