### ISSUE TITLE
Make it work with ruby 2.4.0

### ISSUE THREAD

**Issue by alkesh** [wearefriday/spectre#30]
If you try and run spectre using ruby 2.4.0,
the db:schema:load fails with:
```
SystemStackError: stack level too deep
```
Ruby 2.3.0 works fine (I haven't checked with 2.3.3)

**Comment by nickdunn** [comment]
http://stackoverflow.com/questions/41504106/ruby-2-4-and-rails-4-0-8-stack-level-too-deep-systemstackerror suggests upgrading to Rails 5 might fix this...

**Comment by alkesh** [comment]
also – Rails 4.2.8 (due tomorrow, 15th Feb), will be ruby 2.4.0 compatible.
http://weblog.rubyonrails.org/2017/2/10/Rails-4-2-8-rc1-has-been-released/

**Comment by Firefishy** [comment]
Upgraded to Ruby 2.5.3 and Rails 5.0.x
