### ISSUE TITLE
when screenshot differences are small, the baseline is replaced with the new screenshot, but should remain unchanged

### ISSUE THREAD

**Issue by YmerejRedienhcs** [wearefriday/spectre#36]
when screenshot differences are small, the baseline is replaced with the new screenshot, but should remain unchanged

STR:

1. Replace demo_test_run with the one in the zip file 
[demo_test_run.zip](https://github.com/wearefriday/spectre/files/789009/demo_test_run.zip)
attached to this issue.
1. Invoke demo_test_run with the argument "baseline" (e.g., `docker-compose run --rm app bin/demo_test_run http://app:3000 baseline`) and view the screenshot comparison in the Spectre UI.
    ![image](https://cloud.githubusercontent.com/assets/521773/23149950/85827fa8-f7bd-11e6-9e92-bc96d01945a1.png)
1. Invoke demo_test_run with the argument "fail_small" (e.g., `docker-compose run --rm app bin/demo_test_run http://app:3000 fail_small`) and view the screenshot comparison in the Spectre UI.  Note that the difference is not big enough to cause the test to fail, but it is noted as "0.05% difference".
    ![image](https://cloud.githubusercontent.com/assets/521773/23150051/5986e58c-f7be-11e6-9204-779b9ed841ea.png)
1. Invoke demo_test_run _again_ with the argument "fail_small" and view the screenshot comparison in the Spectre UI.  
    ![image](https://cloud.githubusercontent.com/assets/521773/23150270/5d8c2a96-f7c0-11e6-8487-3533ac78dead.png)
  **Observed**: The newly created screenshot is shown as the baseline.
  **Expected**: The original baseline screenshot will still be shown as the baseline. 

Notes: 

I noticed this because I ran a test where the output in a failed case differed only slightly (two words were translated incorrectly) in such a way that the difference was not large enough to be considered a comparison failure.  My Selenium test compared the text and the test also used Spectre screen comparison.  When I ran the test again, the test still failed because the text was still different, but this time the screen comparison stated that there was no difference at all, not even the small (e.g., 0.03%) difference that had originally been reported.

A scenario in which this bug could manifest itself with very bad effect would be the following: each time a test is run, a particular piece of text shifts by one pixel further to the right each time.  Each time, the baseline gets replaced with the new (shifted baseline), and so eventually, the text is in a completely different location.  If it were compared to the original baseline, it would be noted as a failure, but since a new baseline is computed on each trial, the failure is never reported.

I have only observed this unexpected baseline replacement to occur on "passes".  If I run demo_test_run with "baseline" (run twice or set as baseline as necessary) "fail_large", and "fail_larger", and "fail_larger" the original baseline is, as expected, not replaced in any of these runs.

**Comment by nickdunn** [comment]
Thank you for taking the time to compile such a comprehensive bug report, Jeremy.

Spectre will always update the baseline for a successful test for the very case that you raised — you might want to permit very small variances between tests (e.g. changing a typo, an icon etc) so if the test automatically passes, the baseline should reflect the very latest.

In reality the fuzz level and minimum diff level that Spectre uses is actually there to smooth over issues when using phantomjs for taking screenshots. We found (as did BBC's wraith that we lifted from) that each phantomjs run might antialias differently resulting in a fail. The fuzz level and minimum diff level allow for just enough variation that these pass, while unintended changes do not.

Except you found an unintended change that flew under the radar.

Could the solution be to simply reduce the pass threshold?
