### ISSUE TITLE
Filter by Projects

### ISSUE THREAD

**Issue by jankcat** [wearefriday/spectre#37]
Hello,

I am not sure how easily this can be done, but it would be great to be able to filter by projects, like how you can filter by suites.

Example, you have three projects, each with 5 suites. The dashboard currently shows all the projects and suites in one. Ideally, tapping the project name would bring the user to a page with suite that just belong to that project (instead of all projects' suites).

On a suite page (as well as on test run pages) it shows something like the following near the top: "Projects > ProjectName > SuiteName". Right now, clicking a project name brings the user back to the root /projects page. Ideally, it would bring the user to "https://specre_url/projects/{projectname}/suites/" or similar, so we can see all the suites just for that project.

I am not a ruby guy so it would be harder for me to contribute, but if you can point me in the right direction I would be glad to help with it too.

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
