### ISSUE TITLE
Cannot run Spectre via docker-compose from Ubuntu Desktop 16

### ISSUE THREAD

**Issue by namgivu** [wearefriday/spectre#40]
I follow the running [guide here](https://github.com/wearefriday/spectre#running-using-docker)  which executes the command 

```
docker-compose run --rm app bundle exec rake db:setup
```

I got the error which say something like

> kwargs_from_env() got an unexpected keyword argument 'environment'

My [google search](https://www.google.com.vn/search?q=kwargs_from_env()+got+an+unexpected+keyword+argument+%27environment%27&oq=kwargs_from_env()+got+an+unexpected+keyword+argument+%27environment%27&aqs=chrome..69i57.829j0j7&sourceid=chrome&ie=UTF-8#newwindow=1&q=docker-compose+kwargs_from_env()+got+an+unexpected+keyword+argument+'environment') leads me [this post](https://github.com/wearefriday/spectre#running-using-docker) and gives me the below command that fixes the issue.

```
sudo pip install --upgrade 'docker-py>=1.9.0' #fix error ref. https://github.com/docker/compose/issues/3973#issuecomment-249300447
```

My question, is it correct way to run Spectre?

**Comment by NicoHaase** [comment]
Same here, after pulling the spectre image manually and calling docker-compose, the only output is:

```
nico@nico-VirtualBox:~/spectre$ docker-compose run --rm app bundle exec rake db:setup
Starting spectre_db_1 ... done
Could not locate Gemfile or .bundle/ directory
```

**Comment by Firefishy** [comment]
`docker-compose build` will likely fix the issue. Alternatively upgrade `docker-compose` version.
Re-open if you still have the issue.
