### ISSUE TITLE
Cannot call Spectre API endpoint `POST /runs`

### ISSUE THREAD

**Issue by namgivu** [wearefriday/spectre#41]
After get Spectre run with some effort as reported [here](https://github.com/wearefriday/spectre/issues/40), I can run the web app at **localhost:3000**

Though, when I call the API endpoint `POST /runs` at **localhost:3000/runs with POST** method using Postman, it results in error

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

The web app localhost:3000 also fail now with the same error.

So, how can I get the API work?

**Comment by PrabhatPandey** [comment]
Were you able to get this working ?

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
