### ISSUE TITLE
Use of local filesystem makes hosting on Heroku a no-go

### ISSUE THREAD

**Issue by suan** [wearefriday/spectre#42]
Any thought on using something like S3 instead? Or letting the user use any filesystem that `fog` supports?

Until such a change is made I highly recommend removing Heroku as a possible option on the README

**Comment by lanej0** [comment]
I've found that it's pretty easy to adapt.  spectre uses the Dragonfly gem for file storage, and there's an S3 variant.  So all you need to do is:

Add:

```
gem 'dragonfly-s3_data_store'
```
To your Gemfile, bundle install and then tweak config/inializers/dragonfly.rb to include:

```
require 'dragonfly/s3_data_store'
```
at the top and 

```
datastore :s3,
  bucket_name: 'YOUR-S3-BUCKET',
  access_key_id: 'YOUR_ACCESS_KEY',
  secret_access_key: 'YOUR_SECRET_ACCESS_KEY'
```
under the Dragonfly.app.configure do section.  Just like magic, Heroku works well!

**Comment by Firefishy** [comment]
Alternatively possibly the paperclip gem could be used. Paperclip supports many different cloud storage options.

**Comment by Firefishy** [comment]
Any chance you can PR this change?

**Comment by lanej0** [comment]
@Firefishy I've got it all ready to go locally.  Add me in so I can publish the branch?

**Comment by lanej0** [comment]
I've still got the the pull request ready to go, but I don't have permission to publish it to GitHub.  I'm happy to share it, just let me know

@Firefishy

**Comment by cameronbraid** [comment]
Supporting S3 out of the box would be a great feature

**Comment by cameronbraid** [comment]
I implemeneted a version that uses S3 for storage, which also works with non AWS S3, such as IBM Cloud S3, and minio

https://github.com/cameronbraid/spectre/commit/2237bedec6ca315a2b20f4c2b52ecbf655f7e32b

However , it doesn't fully store everything in S3 due to the way thumbnails are implemented - they are stored in the system/dragonfly/#{Rails.env}/thumbnails folder.  So to fully support S3 the thumbnails need to be migrated to use the dragonfly api as well.

**Comment by cameronbraid** [comment]
I'm not a ruby programmer, however from my research it looks like a dragonfly upfront processor could be used to do the thumbnails http://markevans.github.io/dragonfly/models#up-front

**Comment by cameronbraid** [comment]
I implement thumbnails using dragonfly https://github.com/cameronbraid/spectre/commit/4496c70636d04924d95e5293d55f7a48e8677153

**Comment by calaway** [comment]
@lanej0, instead of having the maintainer give you write access to this repo, you can fork it and submit a PR from your fork back to the original. This is a typical pattern for open source contributions.

I need the same thing, so it would be great to see your solution. Thank you, sir.

**Comment by lanej0** [comment]
@calaway Thanks -- it's my first time contributing.  I've opened a PR (above) -- hope it helps folks.

**Comment by fionnbharra** [comment]
@lanej0 @calaway I've merged that PR, so closing this issue. Will reopen if people have trouble getting s3 integration working.
