### ISSUE TITLE
Meaningful Heroku Error Messages 

### ISSUE THREAD

**Issue by falvhb** [wearefriday/spectre#45]
I did deploy the app on Heroku which was very easy and I'm also able to submit tests and screenshot.
However, I do receive sometimes generic error messages when accessing test runs.

**Error message:**
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
![image](https://user-images.githubusercontent.com/15211237/30957801-8cf1ec94-a43b-11e7-8d6f-c1a447f0adb0.png)

I checked the logs, but those are empty -> log/production.log
There is also no error message in the Heroku console.

How can I find out what went wrong?
Can you enhance the error messages to give a hint? If it is a database probleme, this would allow us to fix it.

I could not track down the error reason so far. Sometimes there is no response or a timeout from the screenshot endpoint, but this does not always cause the error descriped above.

Thanks!

**Comment by Firefishy** [comment]
Could you retry? The app has been updated and error output should be improved for Heroku.

**Comment by lanej0** [comment]
I've found that installing something like Rollbar helps a lot in tracking down Spectre errors.  They have a free trial that's sufficient for the errors that get generated from this.

**Comment by dsolis-apfm** [comment]
> Could you retry? The app has been updated and error output should be improved for Heroku.

I just did a deploy but it displays the same message

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
