### ISSUE TITLE
Ignore element e.g. image carousel

### ISSUE THREAD

**Issue by WiredFire** [wearefriday/spectre#47]
Hi, 

Is there a way to set an element, like an image carousel, to be ignored in the comparison?  I'm running into false positives (false negatives?) when running against pages with these - not the end of the world but any reason but would be great to be able to reduce overhead on checking the failed pages.

Thanks!

**Comment by nickdunn** [comment]
Not within Spectre, no. Your best bet is to manipulate the page before you take the screenshot (e.g. replace the images in a carousel with a flat colour).

**Comment by WiredFire** [comment]
Thanks for the answer - appreciate it.  I'll do that - blanking out the image carousel seems like a good approach.
