### ISSUE TITLE
Hangup under Mac OSx with Docker

### ISSUE THREAD

**Issue by runningnet** [wearefriday/spectre#48]
Hi, 

If  want to start it via Docker, the things hang up..

```
Building app   
Step 1/11 : FROM ruby:2.3   
 ---> 03ff8cebf24f   
Step 2/11 : WORKDIR /opt    
 ---> Using cache
 ---> d414ae489c27
Step 3/11 : RUN curl -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar -jxf -
 ---> Using cache
 ---> 20e3c36c3bf1
Step 4/11 : RUN apt-get -qq update && apt-get -qq install fontconfig
 ---> Using cache
 ---> b24c1d7747ab
Step 5/11 : RUN ln -s /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/
 ---> Using cache
 ---> cff9be0fd825
Step 6/11 : WORKDIR /app
 ---> Using cache
 ---> 8e34591895e6
Step 7/11 : ADD Gemfile* /app/
 ---> Using cache
 ---> c983e83e7359
Step 8/11 : RUN gem install bundler && bundle config build.nokogiri --use-system-libraries && bundle install --quiet --jobs 16 --retry 5 --without test
 ---> Running in bc46bd296e0d
Successfully installed bundler-1.16.1
1 gem installed
The gemspec at
/usr/local/bundle/bundler/gems/spectre_client-a83cbca5f054/spectre_client.gemspec
is not valid. Please fix this gemspec.
The validation error was '"TODO: Put your gem's website or public repo URL
here." is not a valid HTTP URI'
ERROR: Service 'app' failed to build: The command '/bin/sh -c gem install bundler && bundle config build.nokogiri --use-system-libraries && bundle install --quiet --jobs 16 --retry 5 --without test' returned a non-zero code: 1
```

**Comment by Kachilero** [comment]
I'm getting the same issue on spinning up the repo for the first time.

`╰─➤  bundle install && bundle exec rake db:setup
Your Gemfile lists the gem poltergeist (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Fetching gem metadata from https://rubygems.org/.........
Fetching https://github.com/wearefriday/spectre_client.git
You have one or more invalid gemspecs that need to be fixed.
The gemspec at /usr/local/lib/ruby/gems/2.5.0/bundler/gems/spectre_client-a83cbca5f054/spectre_client.gemspec is not valid. Please fix this gemspec.
The validation error was '"TODO: Put your gem's website or public repo URL here." is not a valid HTTP URI'`

**Comment by skambo** [comment]
Also experiencing similar errors, when spinning up in Docker

- `docker-compose run --rm app bundle exec rake db:setup` fails with the following errors

      The validation error was '"TODO: Put your gem's website or public repo URL
      here." is not a valid HTTP URI'
      ERROR: Service 'app' failed to build: The command '/bin/sh -c gem install bundler && bundle config build.nokogiri --use-system-libraries && bundle install --quiet --jobs 16 --retry 5 --without test' returned a non-zero code: 1

- `docker-compose up` fails with the following error:

      spectre_db_1 is up-to-date
      Recreating spectre_app_1 ...
      Recreating spectre_app_1 ... error

      ERROR: for spectre_app_1  no such image: sha256:6a62063907bc1fc57e7556ae7ef06865a48a6aecb21b0073beae62dc342ba6c9: No such image: sha256:6a62063907bc1fc57e7556ae7ef06865a48a6aecb21b0073beae62dc342ba6c9

      ERROR: for app  no such image: sha256:6a62063907bc1fc57e7556ae7ef06865a48a6aecb21b0073beae62dc342ba6c9: No such image: sha256:6a62063907bc1fc57e7556ae7ef06865a48a6aecb21b0073beae62dc342ba6c9
      ERROR: Encountered errors while bringing up the project.

- same as `docker-compose build` fails too

      $ docker-compose up
      WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
      pip uninstall docker-py; pip uninstall docker; pip install docker
      spectre_db_1 is up-to-date
      Recreating 3d67f2559247_spectre_app_1 ...
      Recreating 3d67f2559247_spectre_app_1 ... error

      ERROR: for 3d67f2559247_spectre_app_1  no such image: sha256:6a62063907bc1fc57e7556ae7ef06865a48a6aecb21b0073beae62dc342ba6c9: No such image: sha256:6a62063907bc1fc57e7556ae7ef06865a48a6aecb21b0073beae62dc342ba6c9

      ERROR: for app  no such image: sha256:6a62063907bc1fc57e7556ae7ef06865a48a6aecb21b0073beae62dc342ba6c9: No such image: sha256:6a62063907bc1fc57e7556ae7ef06865a48a6aecb21b0073beae62dc342ba6c9
      ERROR: Encountered errors while bringing up the project.

**Comment by rhtham** [comment]
Just comment out the following line:  https://github.com/wearefriday/spectre/blob/master/Gemfile#L57

**Comment by Firefishy** [comment]
I believe this has now been fixed. Please re-open if still an issue.
