### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by aleitamar** [wearefriday/spectre#50]
latest commit in `master` is from Jun 14, 2017

**Comment by Firefishy** [comment]
Not at the moment. Patches welcome, and we'll try to get them merged.

**Comment by Firefishy** [comment]
I have picked up some backlog and cleaned up things a bit from PRs.

**Comment by drzraf** [comment]
@LindseyJJ / @octanner (if notified that way)...
Any chance to keep your [renewal fork](https://github.com/octanner/spectre) from making use of a private Gem repository (oct-ruby) (and also open issues on the repo)?

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
