### ISSUE TITLE
Test various Mobile device and browser

### ISSUE THREAD

**Issue by tuan91** [wearefriday/spectre#53]
Hi, is it possible to test various mobile devices  and browser?
If so, how can I do that?
Thank you!

**Comment by lanej0** [comment]
You can.  Spectre doesn't take the screenshots for you.  It just compares them and evaluates the differences between a baseline you've set and any new screenshots.

So it's up to you to take a screenshot (either manually, or through some kind of automation using Appium or whatever) and then submit that.
