### ISSUE TITLE
ERROR: Service 'app' failed to build

### ISSUE THREAD

**Issue by kamal2222ahmed** [wearefriday/spectre#54]
$ docker-compose run --rm app bundle exec rake db:setup
.........
Step 3/11 : RUN curl -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar -jxf -
 ---> Running in 3d5320149fde

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: Service 'app' failed to build: The command '/bin/sh -c curl -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar -jxf -' returned a non-zero code: 2
(base) ✘-1 ~/QA/SPECTRE/spectr

**Comment by Firefishy** [comment]
It seems to build now. Likely a temporary issue with bitbucket or similar.
