### ISSUE TITLE
DB Migration PostgreSQL 9.6

### ISSUE THREAD

**Issue by xXluki98Xx** [wearefriday/spectre#61]
Hey, 
after the last update, i cannot start the Docker Container properly, because the data directory was initialized with postgre 9.4, which is not compatible with 9.6.12

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
