### ISSUE TITLE
Can't see past the previous 5 runs

### ISSUE THREAD

**Issue by lfc-sam** [wearefriday/spectre#63]
Each test suite only shows the previous 5 runs and there doesn't seem to be a way to view earlier runs using the id in the url.

Is there anyway to do this as it would be really useful to view historic changes especially for cross browsing testing?

**Comment by lanej0** [comment]
There's a couple of changes you have to make to keep/display older runs.  In `app/models/suite.rb`, the `purge_old_runs` method (at the bottom), change the offset to the number of runs you want to keep (it's hard-coded to 5 right now, so you could make it 20, 50, 100... whatever).  That will make sure that Spectre keeps your previous runs. 

To actually display them in the listing, under `app/views/suites/show.html.erb`, edit the line that says `<% @suite.runs.reversed.limit(5).each do |run| %>` to `<% @suite.runs.reversed.limit(x).each do |run| %>` (where x is the number you want to display.

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
