### ISSUE TITLE
Error while accessing Spectre application on browser

### ISSUE THREAD

**Issue by amandv** [wearefriday/spectre#91]
Error while accessing Spectre application on browser

[fb146069-19e1-4d29-b142-ec9a5f241978] activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'

[fb146069-19e1-4d29-b142-ec9a5f241978] activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'

[fb146069-19e1-4d29-b142-ec9a5f241978] activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'

[fb146069-19e1-4d29-b142-ec9a5f241978] railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] rack (2.2.2) lib/rack/method_override.rb:24:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] rack (2.2.2) lib/rack/runtime.rb:22:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] rack (2.2.2) lib/rack/sendfile.rb:110:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] railties (5.0.7.2) lib/rails/engine.rb:522:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] puma (3.12.2) lib/puma/configuration.rb:227:in `call'

[fb146069-19e1-4d29-b142-ec9a5f241978] puma (3.12.2) lib/puma/server.rb:674:in `handle_request'

[fb146069-19e1-4d29-b142-ec9a5f241978] puma (3.12.2) lib/puma/server.rb:476:in `process_client'

[fb146069-19e1-4d29-b142-ec9a5f241978] puma (3.12.2) lib/puma/server.rb:334:in `block in run'

[fb146069-19e1-4d29-b142-ec9a5f241978] puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'

I, [2020-11-05T03:50:00.427707 #1] INFO -- : [70176e1d-f42a-4129-b2d9-6a6fdd7c058a] Started GET "/" for 172.18.0.1 at 2020-11-05 03:50:00 +0000

I, [2020-11-05T03:50:00.434823 #1] INFO -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] Started GET "/projects" for 172.18.0.1 at 2020-11-05 03:50:00 +0000

I, [2020-11-05T03:50:00.435655 #1] INFO -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] Processing by ProjectsController#index as HTML

I, [2020-11-05T03:50:00.436505 #1] INFO -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] Rendering projects/index.html.erb within layouts/application

D, [2020-11-05T03:50:00.438361 #1] DEBUG -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] Project Load (0.9ms) SELECT "projects".* FROM "projects"

I, [2020-11-05T03:50:00.498963 #1] INFO -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] Rendered projects/index.html.erb within layouts/application (62.3ms)

I, [2020-11-05T03:50:00.499171 #1] INFO -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] Completed 500 Internal Server Error in 63ms (ActiveRecord: 0.9ms)

F, [2020-11-05T03:50:00.500258 #1] FATAL -- : [7d6ddc74-7e7e-4055-b3a8-378179663360]

F, [2020-11-05T03:50:00.500361 #1] FATAL -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] ActionView::Template::Error (PG::UndefinedTable: ERROR: relation "projects" does not exist

LINE 1: SELECT "projects".* FROM "projects"

^

: SELECT "projects".* FROM "projects"):

F, [2020-11-05T03:50:00.500560 #1] FATAL -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] 13: </tr>

[7d6ddc74-7e7e-4055-b3a8-378179663360] 14: </thead>

[7d6ddc74-7e7e-4055-b3a8-378179663360] 15: <tbody>

[7d6ddc74-7e7e-4055-b3a8-378179663360] 16: <% @projects.includes(:suites).each do |project| %>

[7d6ddc74-7e7e-4055-b3a8-378179663360] 17: <% project.suites.each_with_index do |suite, i| %>

[7d6ddc74-7e7e-4055-b3a8-378179663360] 18: <tr id="project_<%= project.id %>" class="project">

[7d6ddc74-7e7e-4055-b3a8-378179663360] 19: <th><%= project.name %></th>

F, [2020-11-05T03:50:00.501057 #1] FATAL -- : [7d6ddc74-7e7e-4055-b3a8-378179663360]

F, [2020-11-05T03:50:00.501117 #1] FATAL -- : [7d6ddc74-7e7e-4055-b3a8-378179663360] app/views/projects/index.html.erb:16:in `_app_views_projects_index_html_erb___657709373241675594_60940'

**Comment by lanej0** [comment]
Did you bootstrap the database?  I' assuming this is a new install.  Try running `rake db:setup` from within the project directory.

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
