### ISSUE TITLE
What means "fuzzLevel"?

### ISSUE THREAD

**Issue by grafoxy** [wearefriday/spectre#92]
I used wdio-novus-visual-regression-service for integration with Spectre. In the manual (https://webdriver.io/docs/wdio-novus-visual-regression-service.html) I see:
fuzzLevel Number ( default: 30 )
 - number between 0 and 100 that defines the fuzz factor of Spectre's image comparison method. For more details please have a look at Spectre documentation. // Link to documentation is https://github.com/wearefriday/spectre

What is the fuzz factor means?

**Comment by Firefishy** [comment]
Spectre hasn't seen active development for some time. Closing the issue, feel free to open at one of the forks.

Alternatively try a fork with active development:

* https://github.com/lanej0/spectre
* https://github.com/octanner/spectre
