### ISSUE TITLE
Good example of a working project?

### ISSUE THREAD

**Issue by alphex** [wearefriday/spectre#99]
Can anyone share a dump of their configuration files for this?

I'm at a loss of even where to start to try and use this.

I want to do Visual Regression testing of a website between two public facing URLS,  a DEV url and a PROD url, and have it scan a collection of paths in each, at various break points, and then show me the diffs with errors based on a % difference...

Does anyone have something I can start from?    

Thank you.

**Comment by nickdunn** [comment]
I'm afraid Spectre hasn't seen active development for some time. We've found a lot more mileage from https://percy.io which is easy to use and zero maintenance.

**Comment by lanej0** [comment]
Spectre will do the image comparison bit for you and then return either a  pass or a fail.  It helps if you think of it as an API, instead of a tool for testing.

**Comment by Firefishy** [comment]
Alternatively try a fork with active development:

https://github.com/lanej0/spectre
https://github.com/octanner/spectre
